version: '3'

services:
    traefik:
        image: library/traefik:latest
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - '80:80'
            - '8080:8080'
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
    php:
        depends_on:
            - mysql
        build:
            context: ./
            dockerfile: docker/Dockerfile
        volumes:
            - .:/var/www/
    nginx:
        image: nginx:alpine
        links:
            - php
        volumes:
            - .:/var/www/
            - ./docker/nginx/ffxiv.conf:/etc/nginx/conf.d/default.conf
            - ./var/nginx_logs/:/var/log/nginx/
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(`ffxiv-content-checker.local`)"
            - "traefik.http.services.nginx.loadbalancer.server.port=80"
            - "traefik.http.routers.nginx.entrypoints=web"
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: rootp
        restart: always
        volumes:
            - ./docker-data/:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.adminer.rule=Host(`adminer.local`)"
            - "traefik.http.services.adminer.loadbalancer.server.port=8080"
            - "traefik.http.routers.adminer.entrypoints=web"

